version: '3'
services:
  app:
    build: .
    entrypoint: /bin/bash
    stdin_open: true
    tty: true 
    working_dir: /repo
    volumes:
       - /Users/givi/path_to_repo:/repo
    environment:
      VERBOSE: false
      DRY_RUN: true
      GIT_API_TAGGING: false
      GITHUB_WORKSPACE: /repo
      GITHUB_OUTPUT: /github_output_log

      DEFAULT_BRANCH: develop
      BUILD_NUMBER: true
      INITIAL_BUILD_NUMBER: 0
      TAG_CONTEXT: repo
      PRERELEASE: true
      PRERELEASE_SUFFIX: dev
      PRERELEASE_VERSION: false